let ef_colors = [
  "#FEBAC3",
  "#C3EEE6",
  "#E0B4D7",
  "#9ABADD",
  "#FE546A",
  "#B4AEF5",
  "#BFCBB3",
  "#FEBFAC"
];

let players = [
  {
    id: 0,
    ballondor_rank: 1,
    name: "Alexia Putellas",
    club: "FC Barcelona",
    clubnr: "#11",
    nationality: "Spanish",
    nationalteam: "Spain",
    nationalteamnr: "#14",
    nationalteamjoin: "2012",
    date: "4  February 1994",
    clubjoin: "2012",
    ftsquadjoin: "",
    height: "1.73m",
    position: "Midfielder",
    ynt: "U-17 and U-19 teams",
    psclubs: "RCD Espanyol (2010-2011), Levante UD (2011-2012)",
    jclubs: "CE Sabadell, FC Barcelona, RCD Espanyol",
    profimgurl: "/src/images/alexia-putellas-profile1.png",
    actionimgurl: "/src/images/alexia-action.jpeg"
  },
  {
    id: 1,
    ballondor_rank: 2,
    name: "Beth Mead",
    club: "Arsenal WFC",
    clubnr: "#9",
    nationality: "British/English",
    nationalteam: "England (Lionesses)",
    nationalteamnr: "#7",
    nationalteamjoin: "2018",
    date: "9th of May 1995",
    clubjoin: "2017",
    ftsquadjoin: "",
    height: "1.63m",
    position: "Forward",
    ynt: "U-15, U-17, U-19, U-20 and U-23 teams",
    psclubs: "Sunderland AFC (2011-2016)",
    jclubs: "Middlesbrough WFC",
    profimgurl: "/src/images/beth-mead-profile1.png",
    actionimgurl: "/src/images/beth-mead-action.jpeg"
  },
  {
    id: 2,
    ballondor_rank: 3,
    name: "Sam Kerr",
    club: "Chelsea FC",
    clubnr: "#20",
    nationality: "Australian",
    nationalteam: "Australia (Matildas)",
    nationalteamnr: "#20",
    nationalteamjoin: "2009",
    date: "10th of September 1993",
    clubjoin: "2020",
    ftsquadjoin: "",
    height: "1.67",
    position: "Forward",
    ynt: "U-17 and U-20 teams",
    psclubs:
      "Perth Glory FC (2008-2011 & 2014-2019), Sydney FC (2012-2014), Western New York Flash (2013-2014), Sky Blue FC/NY Gothham FC (2015-2017), Chicago Red Stars (2018-2019)",
    jclubs: "Western Knights Soccer Club",
    profimgurl: "/src/images/sam-kerr-profile.png",
    actionimgurl: "/src/images/sam-kerr-action.jpeg"
  },
  {
    id: 3,
    ballondor_rank: 4,
    name: "Lena Oberdorf",
    club: "VfL Wolfsburg",
    clubnr: "#5",
    nationality: "German",
    nationalteam: "Germany",
    nationalteamnr: "#6",
    nationalteamjoin: "2019",
    date: "19th of December 2001",
    clubjoin: "2020",
    ftsquadjoin: "",
    height: "1.74m",
    position: "Midfielder",
    ynt: "U-17, U-19 and U-20 teams",
    psclubs: "SGS Essen (2018-2020)",
    jclubs: "TSG Sprockhovel",
    profimgurl: "/src/images/lena-oberdorf-profile.png",
    actionimgurl: "/src/images/oberdorf-action.jpg"
  },
  {
    id: 4,
    ballondor_rank: 5,
    name: "Aitana Bonmatí",
    club: "FC Barcelona",
    clubnr: "#14",
    nationality: "Spanish",
    nationalteam: "Spain",
    nationalteamnr: "#6",
    nationalteamjoin: "2017",
    date: "18th of January 1998",
    clubjoin: "2012",
    ftsquadjoin: "2016",
    height: "1.61m",
    position: "Midfielder",
    ynt: "U-17, U-19, and U-20 teams",
    psclubs: "",
    jclubs: "CD Ribes, CF Cubelles",
    profimgurl: "/src/images/aitana-bonmati-profile1.png",
    actionimgurl: "/src/images/bonmati-action.jpeg"
  },
  {
    id: 5,
    ballondor_rank: 6,
    name: "Alexandra Popp",
    club: "VfL Wolfsburg",
    clubnr: "#11",
    nationality: "German",
    nationalteam: "Germany",
    nationalteamnr: "#11",
    nationalteamjoin: "2010",
    date: "6th of April 1991",
    clubjoin: "2012",
    ftsquadjoin: "",
    height: "1.74m",
    position: "Forward",
    ynt: "U-15, U-17, U-19 and U-20 teams",
    psclubs: "FFC Recklinghausen (2007-2008), FCR 2001 Duisburg (2008-2012)",
    jclubs: "FC Silschede, FFC Recklinghausen",
    profimgurl: "/src/images/alexandra-popp-profile.png",
    actionimgurl: "/src/images/alexandra-popp-action.webp"
  },
  {
    id: 6,
    ballondor_rank: 7,
    name: "Ada Hegerberg",
    club: "Lyon (Olympique Lyonnaise)",
    clubnr: "#14",
    nationality: "Norwegian",
    nationalteam: "Norway",
    nationalteamnr: "#14",
    nationalteamjoin: "2011",
    date: "6th of April 1991",
    clubjoin: "2014",
    ftsquadjoin: "",
    height: "1.76m",
    position: "Forward",
    ynt: "U-15, U-16, U-17, U-19 and U-20 teams",
    psclubs:
      "Kolbotn IL Fotball (2010-2011), Stabæk Fotball (2012-2013), FFC Turbine Potsdam (2013-2014)",
    jclubs: "Sunndal Fotball",
    profimgurl: "/src/images/ada-hegerberg-profile1.png",
    actionimgurl: "/src/images/ada-hegerberg-action.jpeg"
  },
  {
    id: 7,
    ballondor_rank: 8,
    name: "Wendie Renard",
    club: "Lyon (Olympique Lyonnaise)",
    clubnr: "#3",
    nationality: "French",
    nationalteam: "France",
    nationalteamnr: "#3",
    nationalteamjoin: "2011",
    date: "10th of July 1990",
    clubjoin: "2006",
    ftsquadjoin: "",
    height: "1.87m",
    position: "Defender",
    ynt: "U-19 and U-20 teams",
    psclubs: "",
    jclubs: "Essor-Préchotain, Rapid Club du Lorrain",
    profimgurl: "/src/images/wendie-renard-profile.png",
    actionimgurl: "/src/images/wendie-renard-action.jpeg"
  },
  {
    id: 8,
    ballondor_rank: 9,
    name: "Catarina Macario",
    club: "Lyon (Olympique Lyonnaise)",
    clubnr: "#30",
    nationality: "American/Brazilian",
    nationalteam: "USA",
    nationalteamnr: "#20",
    nationalteamjoin: "2021",
    date: "4th of October 1999",
    clubjoin: "2021",
    ftsquadjoin: "",
    height: "1.70m",
    position: "Midfielder",
    ynt: "U-14, U-15 and U-23 teams",
    psclubs: "Stanford Cardinal (College) (2017-2020)",
    jclubs: "San Diego Surf FC, Torrey Pines Falcons",
    profimgurl: "/src/images/catarina-macario-profile.png",
    actionimgurl: "/src/images/catarina-macario-action.jpeg"
  },
  {
    id: 9,
    ballondor_rank: 10,
    name: "Lucy Bronze",
    club: "FC Barcelona",
    clubnr: "#15",
    nationality: "British/English/Portuguese",
    nationalteam: "England (Lionesses)",
    nationalteamnr: "#2",
    nationalteamjoin: "2013",
    date: "28th of October 1991",
    clubjoin: "2022",
    ftsquadjoin: "",
    height: "1.72m",
    position: "Defender/Right-back",
    ynt: "U-17, U-19, U-20 and U-23 teams",
    psclubs:
      "North Carolina Tar Heels (college) (2009), Sunderland AFC (2007-2010), Everton FC (2010-2012), Liverpool FC (2012-2014), Manchester City FC (2014-2017 & 2020-2022), Lyon (Olympique Lyonnaise) (2017-2020)",
    jclubs: "Sunderland AFC, Blyth Town FC",
    profimgurl: "/src/images/lucy-bronze-profile.png",
    actionimgurl: "/src/images/lucy-bronze-action.jpeg"
  },
  {
    id: 10,
    ballondor_rank: 11,
    name: "Vivianne Miedema",
    club: "Arsenal WFC",
    clubnr: "#11",
    nationality: "Dutch",
    nationalteam: "Netherlands",
    nationalteamnr: "#9",
    nationalteamjoin: "2013",
    date: "15th of July 1996",
    clubjoin: "2017",
    ftsquadjoin: "",
    height: "1.75m",
    position: "Forward",
    ynt: "U-15, U-16, U-17 and U-19 teams",
    psclubs: "SC Heerenveen (2011-2014), FC Bayern Munich (2014-2017)",
    jclubs: "HZVV, VV de Weide",
    profimgurl: "/src/images/vivianne-miedema-profile1.png",
    actionimgurl: "/src/images/vivianne-miedema-action.jpeg"
  },
  {
    id: 11,
    ballondor_rank: 12,
    name: "Christiane Endler",
    club: "Lyon (Olympique Lyonnaise)",
    clubnr: "#1",
    nationality: "Chilean/German",
    nationalteam: "Chile",
    nationalteamnr: "#1",
    nationalteamjoin: "2009",
    date: "23rd of July 1991",
    clubjoin: "2021",
    ftsquadjoin: "",
    height: "1.87m",
    position: "Goalkeeper",
    ynt: "U-20 team",
    psclubs:
      "Unión la Calera (2008-2009), Everton de Viña del Mar (2010), Colo-Colo (2011-2012 & 2015-2016), South Florida Bulls (college) (2012-2014), Chelsea FC (2014), Valencia CF (2016-2017), Paris Saint-Germain (2017-2021)",
    jclubs: "",
    profimgurl: "/src/images/christiane-endler-profile.png",
    actionimgurl: "/src/images/christiane-action.jpeg"
  },
  {
    id: 12,
    ballondor_rank: 13,
    name: "Alex Morgan",
    club: "San Diego Wave FC",
    clubnr: "#13",
    nationality: "American",
    nationalteam: "USA",
    nationalteamnr: "#13",
    nationalteamjoin: "2010",
    date: "2nd of July 1989",
    clubjoin: "2022",
    ftsquadjoin: "",
    height: "1.70m",
    position: "Forward",
    ynt: "U-20 team",
    psclubs:
      "California Golden Bears (college) (2007-2010), West Coast FC (2008-2009), California Storm (2010), Pali Blues (2010), Western New York Flash (2011), Seattle Sounders/Sound FC (2012), Portland Thorns FC (2013-2015), Orlando Pride (2016, 2017-2020 & 2021), Lyon (Olympique Lyonnaise) (2017), Tottenham Hotspur FC (2020)",
    jclubs: "American Youth Soccer Organization (AYSO)",
    profimgurl: "/src/images/aitana-bonmati-profile.png",
    actionimgurl: "/src/images/alex-morgan-action.jpeg"
  },
  {
    id: 13,
    ballondor_rank: 14,
    name: "Selma Bacha",
    club: "Lyon (Olympique Lyonnaise)",
    clubnr: "#4",
    nationality: "French",
    nationalteam: "France",
    nationalteamnr: "#13",
    nationalteamjoin: "2021",
    date: "9th of November 2000",
    clubjoin: "2009",
    ftsquadjoin: "2017",
    height: "1.61m",
    position: "Defender/Left-back & Midfielder/Left-winger",
    ynt: "U-16, U-17, U-19, U-20 & U-23 teams",
    psclubs: "",
    jclubs: "FC Gerland",
    profimgurl: "/src/images/aitana-bonmati-profile.png",
    actionimgurl: "/src/images/selma-bacha-action.jpeg"
  },
  {
    id: 14,
    ballondor_rank: 15,
    name: "Millie Bright",
    club: "Chelsea",
    clubnr: "#4",
    nationality: "British/English",
    nationalteam: "England (Lionesses)",
    nationalteamnr: "#5",
    nationalteamjoin: "2016",
    date: "21st of August 1993",
    clubjoin: "2015",
    ftsquadjoin: "",
    height: "approx. 1.75m",
    position: "Defender",
    ynt: "U-19 & U-23 teams",
    psclubs:
      "Doncaster Rovers Belles FC (2009-2014), Leeds United (2011-2012) (Loan)",
    jclubs: "Killamarsh Dynamos, Sheffield United FC",
    profimgurl: "/src/images/aitana-bonmati-profile.png",
    actionimgurl: "/src/images/millie-bright-action.webp"
  },
  {
    id: 15,
    ballondor_rank: 16,
    name: "Asisat Oshoala",
    club: "FC Barcelona",
    clubnr: "#20",
    nationality: "Nigerian",
    nationalteam: "Nigeria",
    nationalteamnr: "#8",
    nationalteamjoin: "2013",
    date: "9 October 1994",
    clubjoin: "2019",
    ftsquadjoin: "",
    height: "1.73m",
    position: "Forward",
    ynt: "U-20 team",
    psclubs:
      "FC Robo Queens (2009-2013), Rivers Angels FC (2013-2015), Liverpool FC (2015-2016), Arsenal FC (2016-2017), Dalian FC/Dalian Quanjian FC (2017-2019)",
    jclubs: "FC Robo Queens",
    profimgurl: "/src/images/asisat-oshoala-profile.png",
    actionimgurl: "/src/images/asisat-oshoala-action.jpeg"
  },
  {
    id: 16,
    ballondor_rank: 17,
    name: "Marie-Antoinette Katoto",
    club: "Paris Saint-Germain",
    clubnr: "#9",
    nationality: "French",
    nationalteam: "France",
    nationalteamnr: "#9",
    nationalteamjoin: "2018",
    date: "1st of November 1998",
    clubjoin: "2011",
    ftsquadjoin: "2015",
    height: "1.77m",
    position: "Forward",
    ynt: "U-16, U-17, U-19, U-20 & U-23 teams",
    psclubs: "",
    jclubs: "Colombes FFC",
    profimgurl: "/src/images/aitana-bonmati-profile.png",
    actionimgurl: "/src/images/marie-antoinette-katoto-action.jpeg"
  },
  {
    id: 17,
    ballondor_rank: 18,
    name: "Trinity Rodman",
    club: "Washington Spirit",
    clubnr: "#2",
    nationality: "American",
    nationalteam: "USA",
    nationalteamnr: "#6",
    nationalteamjoin: "2022",
    date: " 20th of May 2002",
    clubjoin: "2021",
    ftsquadjoin: "",
    height: "1.78m",
    position: "Forward",
    ynt: "U-17 & U-20 teams",
    psclubs: "Washington State Cougars (college)",
    jclubs: "So Cal Blues",
    profimgurl: "/src/images/aitana-bonmati-profile.png",
    actionimgurl: "/src/images/trinity-rodman-action.jpeg"
  },
  {
    id: 18,
    ballondor_rank: 19,
    name: "Fridolina Rolfö",
    club: "FC Barcelona",
    clubnr: "#16",
    nationality: "Swedish",
    nationalteam: "Sweden",
    nationalteamnr: "#18",
    nationalteamjoin: "2015",
    date: "24th of November 1993",
    clubjoin: "2021",
    ftsquadjoin: "",
    height: "1.78m",
    position: "Defender, Midfielder & Forward",
    ynt: "U-19 team",
    psclubs:
      "Tölö IF (2008-2010), Jitex BK (2011-2013), Linköpings FC (2014-2016), FC Bayern Munich (2017-2019), VfL Wolfsburg (2019-2021)",
    jclubs: "IFK Fjärås",
    profimgurl: "/src/images/fridolina-rolfo-profile.png",
    actionimgurl: "/src/images/fridolina-rolfo-action.jpeg"
  },
  {
    id: 19,
    ballondor_rank: 20,
    name: "Kadidiatou Diani",
    club: "Paris Saint-Germain",
    clubnr: "#11",
    nationality: "French",
    nationalteam: "France",
    nationalteamnr: "#11",
    nationalteamjoin: "2014",
    date: "1st of April 1995",
    clubjoin: "2017",
    ftsquadjoin: "",
    height: "1.68m",
    position: "Forward",
    ynt: "U-17, U-19 & U-20 teams",
    psclubs: "FCF Juvisy/Paris FC (2011-2017)",
    jclubs: "ES Vitry, US Ivry, FCF Juvisy/Paris FC",
    profimgurl: "/src/images/aitana-bonmati-profile.png",
    actionimgurl: "/src/images/kadidiatou-diani-action.jpeg"
  }
];

function addPlayerLink(id, element, text) {
  let efLink = document.createElement("a");
  efLink.setAttribute("href", "player-profile.html?player=" + id);
  if (text) {
    efLink.innerText = text;
  }
  element.appendChild(efLink);
  return efLink;
}

function calcColor(rank) {
  return ef_colors[(rank - 1) % ef_colors.length];
}

export { players, addPlayerLink, calcColor };
